### ISSUE TITLE
Adding weights to new users only has to happen on load

### ISSUE THREAD

**Issue by DriesMeerman** [MichielvanBeers/who-needs-to-share-the-board#6]
https://github.com/MichielvanBeers/who-needs-to-share-the-board/blob/5d3090858f60a6adefe2c0afe3ca3188a394bc6c/script.js#L65

Currently missing users are added to the weight every-time someone is picked.
This will only do something the first time, after that it's wasting CPU cycles.

**Comment by kevinvanrossum** [comment]
See my mention in PR #7 where I fixed this

**Comment by DriesMeerman** [comment]
Closing problem solved in #7 like @kevinvanrossum mentioned.
